### ISSUE TITLE
Is it possible to add reckless logging lib?

### ISSUE THREAD

**Issue by pengxu7** [RafaGago/logger-bench#4]
thanks.

**Comment by pengxu7** [comment]
Seems you have included it before.

**Comment by RafaGago** [comment]
Sorry for the late reply, I'm on parental leave away from computers.

If I remember correctly (and I can be wrong) Reckless didn't behave well with this type of testing. I vaguely remember some incorrect Thread Local Storage issues when restarting the logger multiple times.

Pull Requests are welcome.
